import { ArrowRight, Check, ChevronDown, Sparkles, Wand2, Upload, ImagePlus, ShieldCheck } from "lucide-react";
import React, { type ComponentType } from "react";
import { Button } from "@/components/ui/button";
import AuthDialog from "@/components/AuthDialog";
import ProfileMenu from "@/components/ProfileMenu";
import { useAuth } from "@/_core/hooks/useAuth";
import { useState } from "react";
import { Link, useLocation } from "wouter";

const categories = [["👟", "Chaussures", "Laissez la matière et la silhouette parler."], ["👗", "Mode", "Des silhouettes qui arrêtent le scroll."], ["💄", "Beauté", "Des textures visibles, un rendu premium."], ["🍔", "Alimentation", "Donnez envie avant même la première bouchée."], ["📱", "Électronique", "Un produit net, au centre de l'attention."], ["💎", "Bijoux", "La lumière juste pour chaque détail."], ["📦", "Autre", "Votre idée, notre direction artistique."]];
const scenes = [["✦", "Luxury Studio", "Lumière sculptée, fond sophistiqué."], ["○", "Minimal Studio", "Épuré, lumineux, immédiatement lisible."], ["◌", "Lifestyle", "Une scène vivante qui raconte l'usage."], ["↗", "Outdoor", "Naturel, frais, pensé pour les réseaux."], ["◉", "African Lifestyle", "Des ambiances locales, contemporaines et premium."], ["▣", "Social Media Ad", "Un impact visuel conçu pour convertir."]];

export default function Home() {
  const [authOpen, setAuthOpen] = useState(false);
  const [authMode, setAuthMode] = useState<"login" | "recovery">("login");
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const openLogin = () => {
    setAuthMode("login");
    setAuthOpen(true);
  };
  const openRecovery = () => {
    setAuthMode("recovery");
    setAuthOpen(true);
  };
  const openCreateStudio = () => {
    if (user) {
      setLocation("/create");
      return;
    }
    openLogin();
  };

  return <div className="marketing-page min-h-screen bg-[#fbfaf6] text-[#241846]">
    <header className="sticky top-3 z-40 mx-3 rounded-2xl border border-[#241846]/10 bg-[#fbfaf6]/95 shadow-[0_12px_35px_-24px_rgba(36,24,70,.55)] backdrop-blur-xl sm:mx-5"><div className="container flex h-[4.5rem] min-w-0 items-center justify-between gap-1 overflow-visible sm:h-20 sm:gap-3"><Link href="/" className="flex min-w-0 flex-1 items-center gap-2 sm:gap-3"><span className="relative block h-11 w-[138px] shrink-0 overflow-hidden rounded-md bg-transparent px-1 sm:h-14 sm:w-[250px] sm:px-2"><img src="https://primeai-idtu68mc.manus.space/manus-storage/prime-visual-africa-logo-transparent_545a9c76.png" alt="Prime Visual Africa" className="h-full w-full object-contain" /></span><span className="sr-only">Prime Visual AI Studio</span></Link><nav className="hidden items-center gap-8 text-sm font-medium md:flex"><a href="#fonctionnement">Fonctionnement</a><a href="#scenes">Scènes</a><a href="#tarifs">Tarifs</a><a href="#faq">FAQ</a></nav><div className="flex shrink-0 items-center gap-1 sm:gap-3">{user ? <ProfileMenu /> : <><button className="hidden text-sm font-semibold sm:block" onClick={openLogin}>Se connecter</button><button className="hidden text-xs text-[#241846]/50 lg:block" onClick={openLogin}>Créer un compte</button><button className="hidden text-xs text-[#241846]/50 xl:block" onClick={openRecovery}>Mot de passe oublié ?</button><Button onClick={openLogin} className="min-w-[122px] shrink-0 justify-center whitespace-nowrap rounded-full bg-[#241846] px-2 text-[0.72rem] hover:bg-[#39286b] sm:px-5 sm:text-sm">Commencer <ArrowRight className="ml-1.5 h-4 w-4" /></Button></>}</div></div></header>
    <main className="overflow-x-hidden pt-3 sm:pt-5">
      <section className="relative overflow-hidden bg-[#241846] text-white"><div className="absolute inset-0 grain opacity-30" /><div className="container relative grid min-h-[620px] items-center gap-10 py-12 sm:min-h-[680px] sm:gap-16 sm:py-20 lg:grid-cols-[1.02fr_.98fr]"><div className="max-w-2xl"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm text-[#eadb9b]"><Sparkles className="h-4 w-4" /> Le studio créatif des marques ambitieuses</div><h1 className="text-[2.65rem] font-semibold leading-[1.02] tracking-[-0.05em] sm:text-6xl lg:text-7xl">Transformez vos photos produits en <span className="text-[#d8b65c]">visuels professionnels</span> avec l'IA</h1><p className="mt-5 max-w-xl sm:mt-7 text-lg leading-8 text-white/70">Créez des images commerciales pour votre boutique, Instagram, Facebook et WhatsApp sans studio photo coûteux.</p><div className="mt-7 flex flex-col sm:mt-9 gap-3 sm:flex-row"><Button onClick={openCreateStudio} size="lg" className="h-14 rounded-full bg-[#d8b65c] px-7 text-[#241846] hover:bg-[#eadb9b]">Créer mon premier visuel <ArrowRight className="ml-2 h-5 w-5" /></Button><a href="#fonctionnement" className="inline-flex h-14 items-center justify-center rounded-full border border-white/20 px-7 font-semibold text-white/80 hover:bg-white/10">Voir comment ça marche</a></div><div className="mt-10 flex flex-wrap gap-6 text-sm text-white/60"><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#d8b65c]" /> Simple à utiliser</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#d8b65c]" /> Pensé pour le mobile</span><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#d8b65c]" /> En français</span></div></div><div className="relative mx-auto w-full max-w-[520px]"><div className="absolute -inset-6 rounded-[3rem] bg-[#8d6adf]/25 blur-3xl" /><div className="relative rounded-[2rem] border border-white/15 bg-white/10 p-3 shadow-2xl"><img src="https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=1000&q=85" className="aspect-[4/5] w-full rounded-[1.4rem] object-cover" /><div className="absolute bottom-8 left-8 right-8 rounded-2xl border border-white/20 bg-[#241846]/85 p-4 backdrop-blur"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-white/50">Votre prochain visuel</p><p className="mt-1 font-semibold">Création terminée</p></div><span className="grid h-10 w-10 place-items-center rounded-full bg-[#d8b65c] text-[#241846]"><Check className="h-5 w-5" /></span></div></div></div></div></div></section>
      <section id="fonctionnement" className="container py-24"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#8d6adf]">Une idée. Trois étapes.</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">De la photo brute au visuel qui vend.</h2><p className="mt-5 text-lg leading-8 text-[#241846]/60">Pas besoin d'être designer. Prime Visual vous guide, puis l'IA s'occupe de la direction artistique.</p></div><div className="mt-14 grid gap-5 md:grid-cols-3">{[["01", Upload, "Téléversez votre produit", "Ajoutez une photo depuis votre galerie ou votre appareil photo."], ["02", Wand2, "Choisissez votre univers", "Sélectionnez une catégorie et une scène adaptée à votre ambition."], ["03", ImagePlus, "Recevez votre visuel", "L'IA compose une image publicitaire réaliste, prête à publier."]].map((item) => { const [num, Icon, title, copy] = item as [string, ComponentType<{ className?: string }>, string, string]; return <div key={String(num)} className="rounded-[1.5rem] border border-[#241846]/10 bg-white p-7 shadow-[0_18px_60px_-36px_rgba(36,24,70,.35)]"><div className="flex items-center justify-between"><span className="text-sm font-bold text-[#d8b65c]">{num}</span><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#f0ecfb] text-[#8d6adf]"><Icon className="h-5 w-5" /></span></div><h3 className="mt-12 text-xl font-semibold">{String(title)}</h3><p className="mt-3 leading-7 text-[#241846]/60">{copy}</p></div>; })}</div></section>
      <section className="bg-[#f0ecfb] py-24"><div className="container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#8d6adf]">Avant / Après</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">Le potentiel était déjà là.</h2></div><p className="max-w-md text-[#241846]/60">Une lumière plus juste. Une composition plus forte. Une image qui donne confiance.</p></div><div className="mt-12"><div className="before-after-stage relative mx-auto aspect-[16/9] max-w-5xl overflow-hidden rounded-[1.5rem] border border-[#241846]/10 bg-white p-3 shadow-[0_24px_80px_-42px_rgba(36,24,70,.45)]"><img src="https://primeai-idtu68mc.manus.space/manus-storage/prime-visual-apres_6fc9f84d.webp" alt="Après — visuel produit Prime Visual Africa" className="h-full w-full rounded-xl object-cover" /><div className="before-after-overlay absolute inset-3 overflow-hidden rounded-xl"><img src="https://primeai-idtu68mc.manus.space/manus-storage/prime-visual-avant_bdd30eb9.jpg" alt="Avant — photo produit originale" className="h-full w-full object-cover" /></div><div className="before-after-divider absolute bottom-3 left-1/2 top-3 z-10 w-0.5 bg-white shadow-[0_0_0_1px_rgba(36,24,70,.15),0_0_18px_rgba(36,24,70,.25)]"><span className="absolute left-1/2 top-1/2 grid h-11 w-11 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-4 border-white bg-[#d8b65c] text-[#241846] shadow-lg"><ArrowRight className="h-4 w-4 rotate-180" /><ArrowRight className="absolute ml-4 h-4 w-4" /></span></div><span className="absolute bottom-7 left-7 z-20 rounded-full bg-[#241846]/90 px-4 py-2 text-xs font-bold uppercase tracking-[.15em] text-white">Avant</span><span className="absolute bottom-7 right-7 z-20 rounded-full bg-[#d8b65c] px-4 py-2 text-xs font-bold uppercase tracking-[.15em] text-[#241846]">Après</span></div><p className="mx-auto mt-4 max-w-2xl text-center text-sm text-[#241846]/50">Observez la transformation du même produit, de la photo originale au visuel prêt à publier.</p></div></div></section>
      <section className="container py-24"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#8d6adf]">Pour chaque ambition</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Votre produit, votre catégorie.</h2></div><div className="mt-12 grid grid-cols-2 gap-4 sm:grid-cols-4 lg:grid-cols-7">{categories.map(([emoji, name, copy]) => <div key={name} className="group rounded-[1.3rem] border border-[#241846]/10 bg-white p-4 text-center hover:-translate-y-1 hover:border-[#8d6adf]/50 hover:shadow-xl"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#f7f1e2] text-3xl">{emoji}</div><p className="mt-4 text-sm font-bold">{name}</p><p className="mt-2 hidden text-xs leading-5 text-[#241846]/50 sm:block">{copy}</p></div>)}</div></section>
      <section id="scenes" className="bg-[#241846] py-24 text-white"><div className="container"><div className="max-w-xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#d8b65c]">Votre direction artistique</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Six scènes. Une signature.</h2><p className="mt-5 leading-8 text-white/60">Commencez avec une intention, repartez avec une image qui a du caractère.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{scenes.map(([icon, name, copy]) => <div key={name} className="rounded-[1.4rem] border border-white/10 bg-white/5 p-6 hover:bg-white/10"><div className="flex items-center justify-between"><span className="text-2xl text-[#d8b65c]">{icon}</span><ArrowRight className="h-4 w-4 text-white/30" /></div><h3 className="mt-10 text-lg font-semibold">{name}</h3><p className="mt-2 text-sm leading-6 text-white/55">{copy}</p></div>)}</div></div></section>
      <section id="temoignages" className="bg-[#f7f1e2] py-24"><div className="container"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#8d6adf]">Ils nous font confiance</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Des marques africaines, une image qui avance.</h2><p className="mt-5 text-lg leading-8 text-[#241846]/60">Des équipes qui transforment leurs idées en visuels plus clairs, plus professionnels et plus mémorables.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{[["Thandiwe Mokoena", "Fondatrice, Ubuntu Wellness Co.", "Prime Visual Africa a donné une nouvelle dimension à notre image de marque. Une équipe professionnelle, créative et à l’écoute."], ["Daniel Okafor", "Responsable marketing, NexaTech Solutions", "Un service remarquable, des visuels de grande qualité et un résultat qui dépasse nos attentes. Nous recommandons vivement Prime Visual Africa."], ["Lerato Khumalo", "Directrice, Elevate Events & Media", "Prime Visual Africa a parfaitement donné vie à notre vision. Une équipe réactive, talentueuse et très professionnelle."]].map(([name, role, quote]) => <figure key={name} className="flex h-full flex-col rounded-[1.5rem] border border-[#241846]/10 bg-white p-7 shadow-[0_18px_60px_-36px_rgba(36,24,70,.35)]"><div className="text-4xl leading-none text-[#d8b65c]">“</div><blockquote className="mt-4 flex-1 text-lg leading-8 text-[#241846]/80">{quote}»</blockquote><figcaption className="mt-8 border-t border-[#241846]/10 pt-5"><p className="font-semibold">{name}</p><p className="mt-1 text-sm text-[#241846]/55">{role}</p></figcaption></figure>)}</div></div></section>
      <section id="tarifs" className="container py-24"><div className="text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#8d6adf]">Tarifs simples</p><h2 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">Commencez sans friction.</h2><p className="mx-auto mt-5 max-w-xl text-lg text-[#241846]/60">Testez gratuitement, puis choisissez le rythme qui accompagne votre croissance.</p></div><div className="mx-auto mt-12 grid max-w-5xl gap-5 lg:grid-cols-3">{[["FREE", "0 FCFA", "5 générations / mois", ["Visuels avec filigrane", "Toutes les scènes essentielles"]], ["STARTER", "3 000 FCFA", "50 générations / mois", ["Sans filigrane", "Téléchargement 4:5 et 9:16"]], ["BUSINESS", "15 000 FCFA", "200 générations / mois", ["Templates premium", "Usage commercial", "Support prioritaire"]]].map(([name, price, credits, items], idx) => <div key={String(name)} className={`rounded-[1.5rem] border p-7 ${idx === 1 ? 'border-[#8d6adf] bg-[#241846] text-white shadow-2xl shadow-[#8d6adf]/20' : 'border-[#241846]/10 bg-white'}`}><div className="flex items-center justify-between"><p className="font-bold tracking-wide">{name}</p>{idx === 1 && <span className="rounded-full bg-[#d8b65c] px-3 py-1 text-xs font-bold text-[#241846]">Populaire</span>}</div><p className="mt-8 text-4xl font-semibold">{price}<span className={`ml-2 text-sm font-normal ${idx === 1 ? 'text-white/50' : 'text-[#241846]/40'}`}>/ mois</span></p><p className={`mt-3 text-sm ${idx === 1 ? 'text-[#d8b65c]' : 'text-[#8d6adf]'}`}>{credits}</p><div className={`my-7 h-px ${idx === 1 ? 'bg-white/10' : 'bg-[#241846]/10'}`} />{(items as string[]).map(item => <p key={item} className="mb-4 flex items-start gap-3 text-sm"><Check className={`mt-0.5 h-4 w-4 ${idx === 1 ? 'text-[#d8b65c]' : 'text-[#8d6adf]'}`} />{item}</p>)}<Button onClick={openLogin} className={`mt-5 w-full rounded-full ${idx === 1 ? 'bg-[#d8b65c] text-[#241846] hover:bg-[#eadb9b]' : 'bg-[#241846] text-white hover:bg-[#39286b]'}`}>Choisir {name}</Button></div>)}</div></section>
      <section id="faq" className="bg-[#f7f1e2] py-24"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#8d6adf]">FAQ</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">Les réponses, simplement.</h2></div><div className="space-y-3">{[["Est-ce que je dois savoir utiliser Photoshop ?", "Non. Prime Visual a été pensé pour transformer une photo simple en visuel prêt à publier, sans compétence technique."], ["Puis-je utiliser mes visuels sur Instagram et WhatsApp ?", "Oui. Les formats 4:5 et 9:16 sont conçus pour les usages sociaux les plus courants."], ["L'IA modifie-t-elle mon produit ?", "Notre prompt de génération demande de préserver la forme, les proportions, les matériaux et les détails du produit original."], ["Puis-je commencer gratuitement ?", "Oui. Le plan FREE inclut 5 générations par mois, avec filigrane."]].map(([q, a]) => <details key={q} className="group rounded-2xl border border-[#241846]/10 bg-white p-5"><summary className="flex cursor-pointer list-none items-center justify-between font-semibold">{q}<ChevronDown className="h-5 w-5 transition-transform group-open:rotate-180" /></summary><p className="mt-4 max-w-2xl leading-7 text-[#241846]/60">{a}</p></details>)}</div></div></section>
      <section className="container py-24"><div className="relative overflow-hidden rounded-[2rem] bg-[#241846] px-7 py-16 text-center text-white sm:px-16"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-[#8d6adf]/30 blur-3xl" /><div className="relative"><Sparkles className="mx-auto h-8 w-8 text-[#d8b65c]" /><h2 className="mx-auto mt-6 max-w-2xl text-4xl font-semibold tracking-tight sm:text-5xl">Votre prochain visuel commence par une seule photo.</h2><p className="mx-auto mt-5 max-w-xl text-white/60">Rejoignez les marques qui veulent vendre avec plus de clarté, de confiance et de style.</p><Button onClick={openCreateStudio} size="lg" className="mt-8 rounded-full bg-[#d8b65c] px-7 text-[#241846] hover:bg-[#eadb9b]">Créer mon premier visuel <ArrowRight className="ml-2 h-5 w-5" /></Button></div></div></section>
    </main><footer className="border-t border-white/10 bg-[#241846] px-4 py-10 text-white sm:px-0 sm:py-12"><div className="container flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-white">Prime Visual AI Studio</p><p className="mt-2 text-sm leading-6 text-white/65">Des visuels professionnels pour les marques qui avancent.</p></div><div className="flex flex-col gap-2 text-sm text-white/65 sm:items-end"><span>© 2026 Prime Visual AI Studio</span><span>Créé pour les entrepreneurs africains.</span></div></div></footer>
    <AuthDialog open={authOpen} mode={authMode} onOpenChange={setAuthOpen} />
  </div>;
}
